#LetUsPython
#Chapter3_Question1
msg1='an'
msg2='inferior'
msg3='lawyer'
msg4='with'
msg5='dubious'
msg6='practices'
print(msg1.capitalize(),msg2.capitalize,msg3.capitalize,msg4.capitalize,msg5.capitalize,msg6.capitalize)
